# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Forinov's interface deployment system
# Workflow controls
on:
    # Starts deployment on push or pull request events on master branch
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
# Deployment system jobs
jobs:
    build:
        # Deployment system type
        runs-on: ubuntu-latest
        # Provides multiple supported versions to test the deployment
        strategy:
            fail-fast: true
            matrix:
                node-version: [16.x, 19.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # Deployment system steps
        steps:
            - name: Repository check-out
              uses: actions/checkout@v3
            - name: Node.js setup ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"
            - run: npm i
            - run: npm run build
            - name: FTP-Deploy-Action
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                    server: "ftp.forinov.net"
                    username: "amine.belkheiri@forinov.net"
                    password: "IkCPSeZboASx"
                    server-dir: "interface/"
